### ISSUE TITLE
Support for Magento v 2.1

### ISSUE THREAD

**Issue by 11mb** [webgriffe/module-config-override#1]
Is this module magento 2.1 compatible? If so, is it possible to change the composer.json?

Thx!

**Comment by mmenozzi** [comment]
Hi @11mb,
yes it should be compatible. I just fixed version constraints in composer.json to support 100._._ (^100.0.0).
Thank you for your feedback.

**Comment by 11mb** [comment]
Hi mmeozzi! Thanks for your update. I can't use it yet because your tag 1.0.0 still points to the old version. I think you have to release a new version 1.0.1. You can do this by adding a version number to your compose.json and creating a new tag 1.0.1 that points to the latests commit.

**Comment by mmenozzi** [comment]
Done! Thank you!
