### ISSUE TITLE
Support Magento 2.2

### ISSUE THREAD

**Issue by dredumont** [webgriffe/module-config-override#2]
Are you planning to make this plugin work with the latest release of Magento ?

**Comment by mmenozzi** [comment]
Hi @dredumont, do you mean Magento 2.x ?

**Comment by dredumont** [comment]
Sorry, I meant Magento 2.2.

**Comment by mmenozzi** [comment]
We didn't tested it with Magento 2.2 yet. You?
We use this plugin internally very often so if is not working with 2.2 we'll fix but I don't know when. If you want you can propose a pull request.

**Comment by dredumont** [comment]
Yes, I tested it. Only did a composer update though. I think it's a common issue with most plugins that it requires a newer version of the magento/framework package. 

I just discovered this plugin not so long ago and it's a life-saver for me and my team as we are working with differents environments but with the same database.

I'm not a Magento expert but I'll take a look if I can manage it to work with Magento 2.2. Otherwise, you can be sure that your work won't be useless if you decide to update it :)

**Comment by mmenozzi** [comment]
Hi @dredumont,
we tested the extension on Magento 2.2 and it seems to work fine.
So we fixed the composer versions constraints to get it installable with Magento 2.2 and released the 2.2.0 version of this extension.

**Comment by dredumont** [comment]
Does the Magento 2.2 accepts symfony/yml version 3 ? Because I have my fresh install of Magento 2.2 in local who is at the latest version 2 (2.8.27). I can't do a composer update. It says that 
phpunit/phpunit 4.1.0 requires symfony/yaml ~2.0.

**Comment by mmenozzi** [comment]
Uhm it's weird I tried on a fresh install and it worked.
Anyway we just released the 2.2.1 version which allows `symfony/yaml` ^2.0 or ^3.0.
Let me know if you have more issues.

**Comment by dredumont** [comment]
Awesome, it worked with the 2.2.1 !

Thank you very much ! Keep up the good work !

**Comment by mmenozzi** [comment]
Good! Have a nice day!
