### ISSUE TITLE
Support PHP 7.1

### ISSUE THREAD

**Issue by dredumont** [webgriffe/module-config-override#4]
I was wondering if the plugin would be compatible with PHP 7.1.

Thanks.

**Comment by mmenozzi** [comment]
Never tried. We already use it with 7.0 and it works. I think it should work even with 7.1.

**Comment by dredumont** [comment]
Is it possible to update the composer.json to required 7.1 ?

**Comment by mmenozzi** [comment]
Hi @dredumont,  we've just released the version `2.3.0` which supports PHP 7.1.
